"""Task registry exposed to the rest of the framework."""

from fedlab.tasks.base import TaskSpec
from fedlab.tasks.registry import (
    annotate_model,
    build_optimizer,
    compute_metrics,
    create_loss,
    get_model_config,
    get_model_task,
    get_task,
    list_registered_losses,
    list_registered_metrics,
    list_registered_tasks,
    loss_name,
    loss_plugin,
    metric_names,
    metric_plugin,
    optimizer_name,
    primary_metric,
    primary_metric_mode,
    register_loss,
    register_metric,
    register_task,
    task_plugin,
    task_type,
)

__all__ = [
    "TaskSpec",
    "annotate_model",
    "build_optimizer",
    "compute_metrics",
    "create_loss",
    "get_model_config",
    "loss_name",
    "loss_plugin",
    "metric_names",
    "metric_plugin",
    "optimizer_name",
    "get_model_task",
    "get_task",
    "list_registered_losses",
    "list_registered_metrics",
    "list_registered_tasks",
    "primary_metric",
    "primary_metric_mode",
    "register_loss",
    "register_metric",
    "register_task",
    "task_type",
    "task_plugin",
]
