"""Gradient reconstruction attacks and privacy evaluation helpers."""

from fedlab.security.registry import (
    attack_plugin,
    attack_primary_metric_direction,
    attack_summary_metric_plugin,
    compute_recovery_metric_matrix,
    configured_attack_names,
    get_attack_summary_metric,
    get_recovery_metric,
    list_registered_attack_summary_metrics,
    list_registered_attacks,
    list_registered_recovery_metrics,
    normalize_recovery_metric_name,
    recovery_metric_plugin,
    register_attack,
    register_attack_summary_metric,
    register_recovery_metric,
    resolve_recovery_objective,
    resolve_recovery_threshold,
    run_attacks,
    summarize_metric_values,
)

__all__ = [
    'attack_plugin',
    'attack_primary_metric_direction',
    'attack_summary_metric_plugin',
    'compute_recovery_metric_matrix',
    'get_attack_summary_metric',
    'configured_attack_names',
    'get_recovery_metric',
    'list_registered_attack_summary_metrics',
    'list_registered_attacks',
    'list_registered_recovery_metrics',
    'normalize_recovery_metric_name',
    'recovery_metric_plugin',
    'register_attack',
    'register_attack_summary_metric',
    'register_recovery_metric',
    'resolve_recovery_objective',
    'resolve_recovery_threshold',
    'summarize_metric_values',
    'run_attacks',
]
