includes:
  - ../task/classification.yaml
  - ../runtime/gpu.yaml
  - ../training/default.yaml
  - ../loss/classification.yaml
  - ../evaluation/classification.yaml
  - ../tracking/disabled.yaml
  - ../grpc/default.yaml
