includes:
  - ../common/task_classification.yaml
  - ../common/model_small_cnn.yaml
  - ../common/training_classification.yaml
  - ../common/federated.yaml
  - ../common/evaluation_accuracy.yaml
  - ../common/tracking_disabled.yaml
  - ../common/artifacts_yaml.yaml
  - ../common/grpc_default.yaml
  - ../common/classification_federated_defaults.yaml

data:
  dataset_name: cifar10
  split_dir: ../data/cifar10
  clients: [c1, c2, c3]
  image_shape: [3, 32, 32]
  num_classes: 10
