includes:
  - base_federated.yaml
  - ../common/ega/default.yaml

experiment:
  name: cifar10_ega_classification
  mode: federated
  output_dir: outputs/cifar10_ega_classification

federated:
  algorithm: ega_fedavg
  quantization_seed: 4096
