#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/run_test_matrix_common.sh" 1 test_gpu1

run_train configs/secure_quantized_fedavg.yaml federated outputs/test/secure_qint8_stoch_clip10_noise5e-05_seed2026_pat20   --override federated.quantization_dtype=int8   --override federated.quantization_stochastic_rounding=true   --override federated.quantization_seed=2026   --override privacy.clip_norm=10.0   --override privacy.noise_multiplier=0.00005
run_train configs/secure_quantized_fedavg.yaml federated outputs/test/secure_qint8_stoch_clip10_noise1e-04_seed2026_pat20   --override federated.quantization_dtype=int8   --override federated.quantization_stochastic_rounding=true   --override federated.quantization_seed=2026   --override privacy.clip_norm=10.0   --override privacy.noise_multiplier=0.0001
run_train configs/secure_quantized_fedavg.yaml federated outputs/test/secure_qint8_stoch_clip10_noise2e-04_seed2026_pat20   --override federated.quantization_dtype=int8   --override federated.quantization_stochastic_rounding=true   --override federated.quantization_seed=2026   --override privacy.clip_norm=10.0   --override privacy.noise_multiplier=0.0002
run_train configs/secure_quantized_fedavg.yaml federated outputs/test/secure_qint8_stoch_clip10_noise3e-04_seed2026_pat20   --override federated.quantization_dtype=int8   --override federated.quantization_stochastic_rounding=true   --override federated.quantization_seed=2026   --override privacy.clip_norm=10.0   --override privacy.noise_multiplier=0.0003
run_train configs/secure_quantized_fedavg.yaml federated outputs/test/secure_qint8_stoch_clip12_noise5e-05_seed2026_pat20   --override federated.quantization_dtype=int8   --override federated.quantization_stochastic_rounding=true   --override federated.quantization_seed=2026   --override privacy.clip_norm=12.0   --override privacy.noise_multiplier=0.00005
run_train configs/secure_quantized_fedavg.yaml federated outputs/test/secure_qint8_stoch_clip12_noise1e-04_seed2026_pat20   --override federated.quantization_dtype=int8   --override federated.quantization_stochastic_rounding=true   --override federated.quantization_seed=2026   --override privacy.clip_norm=12.0   --override privacy.noise_multiplier=0.0001
run_train configs/secure_quantized_fedavg.yaml federated outputs/test/secure_qint8_stoch_clip12_noise2e-04_seed2026_pat20   --override federated.quantization_dtype=int8   --override federated.quantization_stochastic_rounding=true   --override federated.quantization_seed=2026   --override privacy.clip_norm=12.0   --override privacy.noise_multiplier=0.0002
run_train configs/secure_quantized_fedavg.yaml federated outputs/test/secure_qint8_stoch_clip15_noise5e-05_seed2026_pat20   --override federated.quantization_dtype=int8   --override federated.quantization_stochastic_rounding=true   --override federated.quantization_seed=2026   --override privacy.clip_norm=15.0   --override privacy.noise_multiplier=0.00005
run_train configs/secure_quantized_fedavg.yaml federated outputs/test/secure_qint8_stoch_clip15_noise1e-04_seed2026_pat20   --override federated.quantization_dtype=int8   --override federated.quantization_stochastic_rounding=true   --override federated.quantization_seed=2026   --override privacy.clip_norm=15.0   --override privacy.noise_multiplier=0.0001
run_train configs/secure_quantized_fedavg.yaml federated outputs/test/secure_qint8_stoch_clip15_noise2e-04_seed2026_pat20   --override federated.quantization_dtype=int8   --override federated.quantization_stochastic_rounding=true   --override federated.quantization_seed=2026   --override privacy.clip_norm=15.0   --override privacy.noise_multiplier=0.0002
