#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

BASE_OUTPUT_ROOT="${BASE_OUTPUT_ROOT:-outputs/oracle_noattack_mae_adam_shortlist_$(date +%Y%m%d_%H%M%S)}"
COMMON_PROJECT_NAME="${PROJECT_NAME:-rare-earth-fl-oracle-noattack-shortlist-adam}"
COMMON_BASE_OUTPUT="${BASE_OUTPUT_ROOT}/noattack_mae"

# Non-EGA baselines plus centralized.
BASE_OUTPUT="${COMMON_BASE_OUTPUT}" \
PROJECT_NAME="${COMMON_PROJECT_NAME}" \
RUNTIME_DEVICE="${RUNTIME_DEVICE:-cuda:0}" \
RUN_TAG=oracle_noattack \
TRACKING_TAG=oracle-noattack \
ATTACK_ENABLED=false \
LOSS_NAME=mae \
LOSS_TAG=mae \
TRAIN_OPTIMIZER=adam \
EVAL_MODE=protocol \
SHUFFLE_TRAIN=true \
MODEL_DROPOUT=0.1 \
FEDERATED_ALGORITHMS=fedavg,topk,qsgd,randomk,sign,adaptive,qint8 \
bash scripts/run_oracle_suite.sh --modes centralized,single_sync

# Default EGA config.
BASE_OUTPUT="${COMMON_BASE_OUTPUT}" \
PROJECT_NAME="${COMMON_PROJECT_NAME}" \
RUNTIME_DEVICE="${RUNTIME_DEVICE:-cuda:0}" \
RUN_TAG=oracle_noattack \
TRACKING_TAG=oracle-noattack \
RUN_CENTRALIZED=false \
ATTACK_ENABLED=false \
LOSS_NAME=mae \
LOSS_TAG=mae \
TRAIN_OPTIMIZER=adam \
EVAL_MODE=protocol \
SHUFFLE_TRAIN=true \
MODEL_DROPOUT=0.1 \
FEDERATED_ALGORITHMS=ega \
EGA_PRETRAIN_DEVICE="${RUNTIME_DEVICE:-cuda:0}" \
bash scripts/run_oracle_suite.sh --modes single_sync

# Shortlisted EGA config 1.
BASE_OUTPUT="${COMMON_BASE_OUTPUT}" \
PROJECT_NAME="${COMMON_PROJECT_NAME}" \
RUNTIME_DEVICE="${RUNTIME_DEVICE:-cuda:0}" \
RUN_TAG=oracle_noattack \
TRACKING_TAG=oracle-noattack \
RUN_CENTRALIZED=false \
ATTACK_ENABLED=false \
LOSS_NAME=mae \
LOSS_TAG=mae \
TRAIN_OPTIMIZER=adam \
EVAL_MODE=protocol \
SHUFFLE_TRAIN=true \
MODEL_DROPOUT=0.1 \
FEDERATED_ALGORITHMS=ega \
EGA_PRETRAIN_DEVICE="${RUNTIME_DEVICE:-cuda:0}" \
EGA_ENCODED_DIM=160 \
EGA_HIDDEN_DIM=1536 \
EGA_RESIDUAL_BLOCKS=3 \
EGA_QUANTIZATION_LEVEL=127 \
EGA_NORMALIZATION_EMA=0.95 \
EGA_PRETRAIN_EPOCHS=150 \
EGA_PRETRAIN_PATIENCE=30 \
EGA_PRETRAIN_LR=0.0003 \
bash scripts/run_oracle_suite.sh --modes single_sync

# Shortlisted EGA config 2.
BASE_OUTPUT="${COMMON_BASE_OUTPUT}" \
PROJECT_NAME="${COMMON_PROJECT_NAME}" \
RUNTIME_DEVICE="${RUNTIME_DEVICE:-cuda:0}" \
RUN_TAG=oracle_noattack \
TRACKING_TAG=oracle-noattack \
RUN_CENTRALIZED=false \
ATTACK_ENABLED=false \
LOSS_NAME=mae \
LOSS_TAG=mae \
TRAIN_OPTIMIZER=adam \
EVAL_MODE=protocol \
SHUFFLE_TRAIN=true \
MODEL_DROPOUT=0.1 \
FEDERATED_ALGORITHMS=ega \
EGA_PRETRAIN_DEVICE="${RUNTIME_DEVICE:-cuda:0}" \
EGA_ENCODED_DIM=160 \
EGA_HIDDEN_DIM=2048 \
EGA_RESIDUAL_BLOCKS=3 \
EGA_QUANTIZATION_LEVEL=159 \
EGA_NORMALIZATION_EMA=0.95 \
EGA_PRETRAIN_EPOCHS=200 \
EGA_PRETRAIN_PATIENCE=40 \
EGA_PRETRAIN_LR=0.0002 \
bash scripts/run_oracle_suite.sh --modes single_sync

# Shortlisted EGA config 3.
BASE_OUTPUT="${COMMON_BASE_OUTPUT}" \
PROJECT_NAME="${COMMON_PROJECT_NAME}" \
RUNTIME_DEVICE="${RUNTIME_DEVICE:-cuda:0}" \
RUN_TAG=oracle_noattack \
TRACKING_TAG=oracle-noattack \
RUN_CENTRALIZED=false \
ATTACK_ENABLED=false \
LOSS_NAME=mae \
LOSS_TAG=mae \
TRAIN_OPTIMIZER=adam \
EVAL_MODE=protocol \
SHUFFLE_TRAIN=true \
MODEL_DROPOUT=0.1 \
FEDERATED_ALGORITHMS=ega \
EGA_PRETRAIN_DEVICE="${RUNTIME_DEVICE:-cuda:0}" \
EGA_ENCODED_DIM=168 \
EGA_HIDDEN_DIM=1536 \
EGA_RESIDUAL_BLOCKS=3 \
EGA_QUANTIZATION_LEVEL=127 \
EGA_NORMALIZATION_EMA=0.98 \
EGA_PRETRAIN_EPOCHS=180 \
EGA_PRETRAIN_PATIENCE=30 \
EGA_PRETRAIN_LR=0.0003 \
bash scripts/run_oracle_suite.sh --modes single_sync
